on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: create remote context
        uses: arwynfr/actions-docker-context@v2
        with:
          docker_host: ssh://ubuntu@144.24.83.69
          context_name: remote
          ssh_key: ${{ secrets.CHUNSIK_SSH_KEY }}
      - name: skip strict host key checking
        run: |
          echo "Host *" >> ~/.ssh/config
          echo "  StrictHostKeyChecking no" >> ~/.ssh/config
      - name: build and deploy to remote
        run: docker --context remote compose up -d --build --force-recreate